[project]
name = 'IntellectualAssetToken'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.IntellectualAssetToken]
path = 'contracts/IntellectualAssetToken.clar'
clarity_version = 3
epoch = 3.0


[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
